# My Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzdmNGU5M2E4MDdlYWVkNjU1ZTQzYTUiLCJpYXQiOjE2NjkyODc2MTksImV4cCI6MTY2OTU0NjgxOX0.RJFbHbP3ktnTDvgSkSDlG09KpIjJVQPtmvGXPvS-23s

### login
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email": "gagan@gagan.com",
    "password": "P@ssw0rd"
}



### POST Request
POST http://localhost:4000/api/workouts/
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title":"Sami Situps",
    "reps":60,
    "load":1
}

### GET Request
GET http://localhost:4000/api/workouts
Content-Type: application/json
Authorization: bearer {{token}}

### GET Request
GET http://localhost:4000/api/workouts/637f20c5b48107f2d9627410
Content-Type: application/json
Authorization: bearer {{token}}
